### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Same thing I implemented in https://github.com/kbknapp/clap-rs/pull/631

Getting a release with this in would be great so I'll do a PR replacing that with this.

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Only Travis fail is from `rustup.sh` not working :v

**Comment by kbknapp** [comment]
Awesome, thanks! @homu r+

**Comment by kbknapp** [comment]
Forgot I don't have homu here...

**Comment by nabijaczleweli** [comment]
xD

**Pull request merged**
